name = "crash-game"
main = "src/server/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[vars]
CRASH_DEBUG = "true"

[[durable_objects.bindings]]
name = "CrashGame"
class_name = "CrashGame"

[[migrations]]
tag = "v1"
new_classes = ["CrashGame"]
